name: Build LaTeX document

on:
  push:
    branches: [ "main" ]

jobs:
  # spell_check:
  #   runs-on: self-hosted
  #
  #   steps:
  #     - name: Set up Git repository
  #       uses: actions/checkout@v4
  #
  #     # https://github.com/marketplace/actions/github-spellcheck-action
  #     # TODO: This action won't work because it can't find the 'spellcheck.yml' file.
  #     #       I tried with different `config_path` configs without any result.
  #     #       We probably need a better action 🤔
  #     - name: Spell Check
  #       uses: rojopolis/spellcheck-github-actions@v0
  #       with:
  #         config_path: .github/spellcheck.yml

  build_latex:
    runs-on: self-hosted

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-action-for-latex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

  release:
    needs: build_latex
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Release Name
        id: relname
        run: |
          echo "tag=build-$(git rev-parse --short HEAD)-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: PDF

      # https://github.com/marketplace/actions/create-release
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.pdf"
          body: ":robot: Lates Latex Build automatically generated by GitHub Actions."
          tag: ${{ steps.relname.outputs.tag }}
